public class Constants {
    // ACCOUNT
    public static final String ACCOUNT_DEPARTMENT_ACCOUNT_NAME = 'Wydziały';
    public static final String ACCOUNT_RECORD_TYPE_BUSINESS_ORGANIZATION_API_NAME = 'Business_Organization';
    public static final String ACCOUNT_RECORD_TYPE_ADMINISTRATIVE_API_NAME = 'Administrative';
    public static final String ACCOUNT_RECORD_TYPE_ACADEMIC_PROGRAM_API_NAME = 'Academic_Program';
    public static final String ACCOUNT_RECORD_TYPE_SPECIALTY_API_NAME = 'DT_Specialty';
    public static final String ACCOUNT_RECORD_TYPE_DEPARTMENT_API_NAME = 'University_Department';
    public static final String ACCOUNT_STATUS_ACTIVE_API_NAME = 'Active';
    public static final String ACCOUNT_TYPE_ACADEMIC_PROGRAM_API_NAME = 'Academic Program';
    public static final String ACCOUNT_TYPE_SPECIALTY_API_NAME = 'Specialty';
    public static final String ACCOUNT_TYPE_PATHWAY_API_NAME = 'Pathway';
    public static final String ACCOUNT_INDUSTRY_OTHER = 'Other';

    // APPROVAL PROCESS
    public static final String CAREER_SERVICES_APPROVAL_PROCESS_STATUS_ACTIVE = 'Active';
    public static final String CAREER_SERVICES_APPROVAL_PROCESS_STATUS_ABANDONED = 'Abandoned';
    public static final String CAREER_SERVICES_APPROVAL_PROCESS_STATUS_FINISHED = 'Finished';
    public static final String CAREER_SERVICES_APPROVAL_PROCESS_STAGE_CAREER_SERVICES_ACCEPTANCE = 'Career_Services_Acceptance';
    public static final String CAREER_SERVICES_APPROVAL_PROCESS_STAGE_SUPERVISOR_ACCEPTANCE = 'Supervisor_Acceptance';
    public static final String CAREER_SERVICES_APPROVAL_PROCESS_RECORD_TYPE_INDIVIDUAL_APPLICATION = 'Individual_Application';
    public static final String CAREER_SERVICES_APPROVAL_PROCESS_RECORD_TYPE_INSTITUTIONAL_APPLICATION = 'Institutional_Application';
    public static final String CAREER_SERVICES_APPROVAL_PROCESS_RECORD_TYPE_INTERNSHIP_OFFER = 'Internship_Offer';

    // APPROVAL PROCESS ENTRY
    public static final String CAREER_SERVICES_APPROVAL_PROCESS_ENTRY_DECISION_RECORD_TYPE = 'Decision';
    public static final String CAREER_SERVICES_APPROVAL_PROCESS_ENTRY_COMMENT_RECORD_TYPE = 'Comment';
    public static final String CAREER_SERVICES_APPROVAL_PROCESS_ENTRY_REMINDER_RECORD_TYPE = 'Reminder';

    // ADMISSIONS DICTIONARY
    public static final String ADMISSIONS_DICTIONARY_RT_CONSENT_DEFINITION_BUNDLE_DEV_NAME = 'TB_Consents_Definitions_Bundle';

    // ADMISSIONS DICTIONARY
    public static final String ADMISSIONS_DICTIONARY_RECORD_TYPE_CONSENT_DEFINITION_BUNDLE_DEV_NAME = 'TB_Consents_Definitions_Bundle';
    public static final String ADMISSIONS_DICTIONARY_USED_ON_CAREER_OFFICE_FORM_API_NAME = 'Career_Office_Form';
    public static final String ADMISSIONS_DICTIONARY_CONSENT_TYPE_TERMS_AND_CONDITIONS = 'Terms and Conditions';
    public static final String ADMISSIONS_DICTIONARY_CONSENT_TYPE_MARKETING = 'Marketing';

    // CAMPAIGN MEMBER
    public static final String CAMPAIGN_MEMBER_STATUS_RESPONDED_API_NAME = 'Responded';
    public static final String CAMPAIGN_MEMBER_STATUS_SENT_API_NAME = 'Sent';

    // CAREER SERVICES APPLICATION
    public static final String CAREER_SERVICES_APPLICATION_OBJECT_API_NAME = 'Career_Services_Application__c';
    public static final String CAREER_SERVICES_APPLICATION_RT_JOB_PLACEMENT_APPLICATION = 'Job_Placement_Application';
    public static final String CAREER_SERVICES_APPLICATION_RT_INSTITUTIONAL_INTERNSHIP = 'Institutional_Internship';
    public static final String CAREER_SERVICES_APPLICATION_RT_INDIVIDUAL_INTERNSHIP = 'Individual_Internship';
    public static final String CAREER_SERVICES_APPLICATION_STATUS_APPLICATION_ACCEPTED = 'Application Accepted';
    public static final String CAREER_SERVICES_APPLICATION_STATUS_CORRECTION_NEEDED = 'Correction Needed';
    public static final String CAREER_SERVICES_APPLICATION_STATUS_NEW_APPLICATION = 'New Application';
    public static final String CAREER_SERVICES_APPLICATION_STATUS_REVERIFICATION = 'Reverification';
    public static final String CAREER_SERVICES_APPLICATION_STATUS_SENT_FOR_SUPERVISOR_ACCEPTANCE = 'Sent for Supervisor\'s Acceptance';
    public static final String CAREER_SERVICES_APPLICATION_STATUS_CS_REJECTION = 'CS Rejection';
    public static final String CAREER_SERVICES_APPLICATION_STATUS_CS_REVERIFICATION = 'CS Reverification';
    public static final String CAREER_SERVICES_APPLICATION_STATUS_SUPERVISOR_REJECTION = 'Supervisor Rejection';
    public static final String CAREER_SERVICES_APPLICATION_STATUS_APPLICATION_SENT_TO_EMPLOYER = 'Application sent to Employer';
    public static final String CAREER_SERVICES_APPLICATION_STATUS_INTERNSHIP_READY_TO_PROCEED = 'Internship Ready to Proceed';
    public static final String CAREER_SERVICES_APPLICATION_STATUS_AGREEMENT_CREATION = 'Agreement Creation';

    // CAREER SERVICES OFFER
    public static final String CAREER_SERVICES_OFFER_OBJECT_API_NAME = 'Career_Services_Offer__c';
    public static final String CAREER_SERVICES_OFFER_RT_JOB_OFFER = 'Job_Offer';
    public static final String CAREER_SERVICES_OFFER_RT_INSTITUTIONAL_INTERNSHIP = 'Institutional_Internship';
    public static final String CAREER_SERVICES_OFFER_RT_INDIVIDUAL_INTERNSHIP = 'Individual_Internship';
    public static final String CAREER_SERVICES_OFFER_BUSINESS_CATEGORY_DESIGN_API_NAME = 'Design';
    public static final String CAREER_SERVICES_OFFER_EMPLOYMENT_TYPE_B2B_API_NAME = 'B2B';
    public static final String CAREER_SERVICES_OFFER_EXTERNAL_SUPERVISOR_EDUCATION_OTHER = 'Other';
    public static final String CAREER_SERVICES_OFFER_LOCATION_OF_SWPS_UNIVERSITY_WARSZAWA_API_NAME = 'Wa';
    public static final String CAREER_SERVICES_OFFER_POSITION_LEVEL_SPECIALIST_API_NAME = 'Specialist';
    public static final String CAREER_SERVICES_OFFER_SALARY_UNPAID = 'Unpaid';
    public static final String CAREER_SERVICES_OFFER_STATUS_PUBLISHED_API_NAME = 'Published';
    public static final String CAREER_SERVICES_OFFER_STATUS_NEW_OFFER = 'New Offer';
    public static final String CAREER_SERVICES_OFFER_WORKPLACE_TYPE_REMOTE = 'Remote';
    public static final String CAREER_SERVICES_OFFER_SECTOR_PRIVATE = 'Private';
    public static final String CAREER_SERVICES_OFFER_STATUS_PUBLISHED = 'Published';
    public static final String CAREER_SERVICES_OFFER_STATUS_SUPERVISOR_VERIFICATION = 'Supervisor\'s Verification';
    public static final String CAREER_SERVICES_OFFER_STATUS_REJECTED = 'Rejected';
    public static final String CAREER_SERVICES_OFFER_STATUS_ARCHIVED_API_NAME = 'Archived';
    public static final String CAREER_SERVICES_OFFER_STATUS_AGREEMENT_CREATION = 'Agreement Creation';

    // CAREER SERVICES OFFER CONTRACT
    public static final String CAREER_SERVICES_OFFER_CONTRACT_RT_INTERNSHIP = 'Internship';
    public static final String CAREER_SERVICES_OFFER_CONTRACT_RECORD_TYPE_JOB_OFFER_API_NAME = 'Job_Offer';
    public static final String CAREER_SERVICES_OFFER_CONTRACT_STATUS_DRAFT_API_NAME = 'Draft';
    public static final String CAREER_SERVICES_OFFER_CONTRACT_STATUS_PUBLISHED_API_NAME = 'Published';
    public static final String CAREER_SERVICES_OFFER_CONTRACT_STATUS_COMPLETED_API_NAME = 'Completed';
    public static final String CAREER_SERVICES_OFFER_CONTRACT_STATUS_EXPIRED_API_NAME = 'Expired';

    // CONSENT
    public static final String CONSENT_STATUS_OPT_IN_API_NAME = 'Opt_In';
    public static final String CONSENT_SOURCE_TYPE_WWW_API_NAME = 'WWW';

    // CONTACT
    public static final String CONTACT_STUDENT_RECORD_TYPE_DEV_NAME = 'TB_Student';
    public static final String CONTACT_PARTNER_RECORD_TYPE_DEV_NAME = 'TB_Partner';
    public static final String CONTACT_PREFERRED_EMAIL_ALTERNATE = 'Alternate';

    // CONTENT DOCUMENT LINK
    public static final String CONTENT_DOCUMENT_LINK_SHARE_TYPE_VIEWER_API_NAME = 'V';
    public static final String CONTENT_DOCUMENT_LINK_VISIBILITY_ALL_USERS_API_NAME = 'AllUsers';

    // CONTRACT
    public static final String CONTRACT_STATUS_NOT_IMPLEMENTED_API_NAME = 'Not_Implemented';

    // EDUCATION HISTORY
    public static final String EDUCATION_HISTORY_STATUS_STUDYING = 'Studying';

    // GROUP
    public static final String GROUP_CAREER_OFFICE_QUEUE_DEVELOPER_NAME = 'DT_Biuro_Karier';

    // INTERNSHIP SUPERVISOR
    public static final String INTERNSHIP_SUPERVISOR_TYPE_SUPERVISOR = 'Supervisor';
    public static final String INTERNSHIP_SUPERVISOR_TYPE_PROXY = 'Proxy';

    // LANGUAGE
    public static final String LANGUAGE_LOCALE_KEY_POLISH = 'pl';

    // NETWORK
    public static final String NETWORK_NAME_MYSWPS = 'MySWPS';

    // OPPORTUNITY
    public static final String OPPORTUNITY_ADDITIONAL_WAYS_OF_COOPERATION_JOB_FAIRS_API_NAME = 'Job Fairs';
    public static final String OPPORTUNITY_ADDITIONAL_WAYS_OF_COOPERATION_JOB_PLACEMENT_API_NAME = 'Job placement';
    public static final String OPPORTUNITY_COOPERATION_NAME_FORMAT = '{0} - {1}';
    public static final String OPPORTUNITY_RECORD_TYPE_CAREER_OFFICE_DEVELOPER_NAME = 'DT_Career_Office';
    public static final String OPPORTUNITY_STAGE_NAME_CLOSED_LOST_API_NAME = 'Closed Lost';
    public static final String OPPORTUNITY_STAGE_NAME_CLOSED_WON_API_NAME = 'Closed Won';
    public static final String OPPORTUNITY_STAGE_NAME_CLOSED_WON_ACCEPTANCE_REPORT_API_NAME = 'Closed Won: Acceptance Report';
    public static final String OPPORTUNITY_STAGE_NAME_NEW_API_NAME = 'New';

    public static final Set<String> OPPORTUNITY_STAGE_NAMES_CLOSED = new Set<String>{
        OPPORTUNITY_STAGE_NAME_CLOSED_LOST_API_NAME,
        OPPORTUNITY_STAGE_NAME_CLOSED_WON_API_NAME,
        OPPORTUNITY_STAGE_NAME_CLOSED_WON_ACCEPTANCE_REPORT_API_NAME
    };

    // PERMISSION SETS
    public static final String PERMISSION_SET_CAREER_SERVICES_ADMINISTRATOR_API_NAME = 'Career_Services_System_Administrator';
    public static final String PERMISSION_SET_CAREER_SERVICES_EMPLOYEE_API_NAME = 'Career_Services_Employee';
    public static final String PERMISSION_SET_CAREER_SERVICES_SUPERVISOR_API_NAME = 'Career_Services_Supervisor';

    // PROFILES
    public static final String PROFILE_SWPS_STUDENT_NAME = 'SWPS Student';
    public static final String PROFILE_SWPS_ADMISSIONS_APPLICANT_NAME = 'SWPS Admissions - Applicant (Plus)';
    public static final String PROFILE_SWPS_CAREER_SERVICES_PROFILE_NAME = 'SWPS Career Office';
    public static final String PROFILE_SWPS_PLATFORM_PROFILE_NAME = 'SWPS Employee Platform User';

    // PROGRAM ENROLLMENT
    public static final String PROGRAM_ENROLLMENT_LEVEL_OF_STUDIES_BACHELOR_API_NAME = 'Bachelor';
    public static final String PROGRAM_ENROLLMENT_MODE_OF_STUDIES_FULL_TIME_API_NAME= 'Full_Time';

    // PROGRAM PLAN
    public static final String PROGRAM_PLAN_MODE_OF_STUDIES_FULL_TIME_API_NAME = 'Full_Time';
    public static final String PROGRAM_PLAN_LANGUAGE_OF_INSTRUCTION_POLISH_API_NAME = 'PL';
    public static final String PROGRAM_PLAN_STATUS_CURRENT = 'Current';

    // RECORD JUNCTION TAG
    public static final String TAG_LEVEL_INTERMEDIATE_API_NAME = 'Intermediate';
    public static final String TAG_LEVEL_ADVANCED_API_NAME = 'Advanced';

    // TAG
    public static final String TAG_CATEGORY_LANGUAGE_API_NAME = 'Language';
    public static final String TAG_ENGLISH_NAME_VALUE_ENGLISH = 'English';
    public static final String TAG_ENGLISH_NAME_VALUE_POLISH = 'Polish';

    // USERS
    public static final String CAREER_SERVICES_PROCESS_AUTOMATION_USER_NAME = 'Process Automation';

    // PROFILES
    public static final String SWPS_PLATFORM_PROFILE_NAME = 'SWPS Employee Platform User';

    // OTHER
    public static final String COMMUNITY_LANG_PL = 'pl';
}