public without sharing class TB_kb_Constants {
    //TEST EXPRESSIONS
    public static final String TEST_EXPRESSION = 'TEST';
    public static final String INVALID_EXPRESSION = 'INVALID';

    //OBJECT API NAMES
    public static final String SUGGESTED_ARTICLE_GROUP_API_NAME ='TB_Suggested_Article_Group__c';  
    public static final String SUGGESTED_ARTICLE_GROUP_ELEMENT_API_NAME ='TB_Suggested_Article_Group_Element__c';  

    //KNOWLEDGE__KAV
    public static final String ONLINE_KAV_PUBLISH_STATUS ='Online';  

    //TB_KNOWLEDGE_CATEGORY__C
    public static final String ADMISSIONS_KNOWLEDGE_CATEGORY_BUSINESS_OWNER = 'Admissions';

    //SUGGESTED ARTICLE GROUP
    
        //RECORD TYPE
    public static final String ASSIGNED_TO_CONTACT_GROUP_SUGGESTED_ARTICLE_GROUP_RT_DEVNAME = 'TB_Assigned_To_Contact_Group';
    public static final String ASSIGNED_TO_SUBCATEGORY_SUGGESTED_ARTICLE_GROUP_RT_DEVNAME = 'TB_Assigned_To_Subcategory';

        //CONTACT GROUP
    public static final String HIGHER_EDUCATION_CONTACT_GROUP_SUGGESTED_ARTICLE_GROUP = 'Higher_Education';
    public static final String POST_GRADUATE_STUDIES_CONTACT_GROUP_SUGGESTED_ARTICLE_GROUP = 'Post_Graduate_Studies';
    public static final String DOCTORAL_SCHOOL_CONTACT_GROUP_SUGGESTED_ARTICLE_GROUP = 'Doctoral_School';
    public static final String FOR_EMPLOYEES_CONTACT_GROUP_SUGGESTED_ARTICLE_GROUP = 'For_Employees';
    public static final String ABOUT_SWPS_UNIVERSITY_CONTACT_GROUP_SUGGESTED_ARTICLE_GROUP = 'About_SWPS_University';
}