@IsTest
public with sharing class TB_MCClientTest {
//    @IsTest
//    private static void createDEEntryAdmissionsTest() {
//        TB_MCClient.WrapperClass wrapper = new TB_MCClient.WrapperClass();
//        wrapper.journey = 'Admissions';
//
//        Test.startTest();
//        TB_MCClient.createDEEntry(new List<TB_MCClient.WrapperClass> {wrapper});
//        Test.stopTest();
//
//        List<AsyncApexJob> asyncJobs = [SELECT Id, ApexClassId, ApexClass.Name FROM AsyncApexJob WHERE JobType = 'BatchApex'];
//        System.assertEquals(1, asyncJobs.size());
//        System.assertEquals('TB_MCAdmissionsQueueableBatch', asyncJobs[0].ApexClass.Name);
//    }
//
//    @IsTest
//    private static void createDEEntryWebFormSubmissionTest() {
//        TB_MCClient.WrapperClass wrapper = new TB_MCClient.WrapperClass();
//        wrapper.journey = 'WebFormSubmission';
//
//        Test.startTest();
//        TB_MCClient.createDEEntry(new List<TB_MCClient.WrapperClass> {wrapper});
//        Test.stopTest();
//
//        List<AsyncApexJob> asyncJobs = [SELECT Id, ApexClassId, ApexClass.Name FROM AsyncApexJob WHERE JobType = 'BatchApex'];
//        System.assertEquals(1, asyncJobs.size());
//        System.assertEquals('TB_MCMauticWebFormQueueableBatch', asyncJobs[0].ApexClass.Name);
//    }

}