public without sharing class TB_vu_Constants {
    //TEST EXPRESSIONS
    public static final String TEST_EXPRESSION = 'TEST';
    public static final String INVALID_EXPRESSION = 'INVALID';

    //CASE
    public static final String MEETING_BOOKED_CASE_STATUS = 'Meeting_Booked';
    public static final String VIRTUAL_UNIVERSITY_CASE_ORIGIN = 'Virtual_University';
    public static final String MEETING_CASE_RECORD_TYPE_DEVELOPER_NAME = 'TB_Student_Meeting_HE';
    public static final String CSS_OFFICE_CASE_ORIGIN = 'CSS_Office';
    public static final String NOTIFICATION_CASE_RECORD_TYPE_DEVELOPER_NAME = 'TB_Student_Notification_HE';
    public static final String CERTIFICATE_CASE_RECORD_TYPE_DEVELOPER_NAME = 'TB_Student_Certificate_HE';
    public static final String QUESTION_CASE_RECORD_TYPE_DEVELOPER_NAME = 'TB_Student_Certificate_HE';


    //OPERATION
    public static final String STUDENT_OPERATION_AUTHOR = 'Student';
    public static final String EXTERNAL_COMMENT_OPERATION_TYPE = 'External_Comment';
    public static final String CONVERSATION_OPERATION_RECORD_TYPE_DEVELOPER_NAME = 'TB_Conversation';

    //EVENT
    public static final String ADVISING_TIME_EVENT_RECORD_TYPE_DEVELOPER_NAME = 'DT_AdvisingTime';
    public static final String BUSY_EVENT_SHOW_AS = 'Busy';
    public static final String MEETING_EVENT_TYPE = 'Meeting';

    //SFAL__APPOINTMENT
    public static final String ADVISING_EVENT_APPOINTMENT_RECORD_TYPE_DEVELOPER_NAME = 'DT_Advising_Event';
    
    //LANGUAGE VALUES
    public static final String LANGUAGE_POLISH = 'PL';

    //CONTENT VERSION
    public static final String STUDENT_NOTIFICATION_CONTENT_VERSION_CATEGORY = 'Student_Notification';
    public static final String CASE_ATTACHMENT_CONTENT_VERSION_CATEGORY = 'Case_Attachment';

    //PROFILE
    public static final String SWPS_STUDENT_PROFILE_NAME = 'SWPS Student';
    public static final String ADMIN_PROFILE_NAME = 'System Administrator';

    //PROGRAM ENROLLMENT
    public static final String CAMPUS_BILLING_CITY_WARSAW = 'Warszawa';
    public static final List<String> PROGRAM_ENROLMENT_LEVEL_OF_STUDIES = new List<String>{
        'Bachelor', 'Master', 'Integrated_Master'
    };

}